version: '3.1'
services:
  use-of-force:
    build: .
    networks:
      - hmpps
    depends_on:
      - use-of-force-db
      - nomis-oauth2-server
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    environment:
    - PORT=3000
    - DB_USER=use-of-force
    - DB_PASS=use-of-force
    - DB_SERVER=use-of-force-db
    - DB_NAME=use-of-force
    - DB_SSL_ENABLED=no
    - NOMIS_AUTH_URL=http://nomis-oauth2-server:8080/auth
    - NOMIS_AUTH_EXTERNAL_URL=http://localhost:8080/auth

  use-of-force-db:
    image: postgres
    networks:
    - hmpps
    container_name: use-of-force-db
    restart: always
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=use-of-force
    - POSTGRES_USER=use-of-force
    - POSTGRES_DB=use-of-force

  nomis-oauth2-server:
    image: mojdigitalstudio/nomis-oauth2-server:latest
    networks:
      - hmpps
    container_name: nomis-oauth2-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  hmpps:
